### ISSUE TITLE
Question about DOM

### ISSUE THREAD

**Issue by robrez** [Prhythm/prism-event-bus#1]
First - great concept.  I've been thinking a simple pub-sub event-bus pattern would be a great way to solve communication between elements and this project certainly fits the bill.  No matter how I try, redux just doesn't feel right to me.

Are there some benefits to creating elements and attaching them to the DOM rather than just creating the bus instances as js Objects?  It seems like this could be pure-javascript

**Comment by nanashi07** [comment]
Yes, this component could be rewrited as a pure javascript function. The reason using component is
* For dependency, component is imported and load once via html import. I don't need to consider where to load it.
* For SPA application, this could load and destroy automatically by owner component or view.

This feature designed based on polymer. In other solution, rewrite as pure javascript may more befitting for usage.

**Comment by robrez** [comment]
Thanks for the info.

You can still import js-only content via an html import (eg: behaviors, polymer.html, etc). Even as js objects, it seems that bus instances could be destroyed by components or views.
